server:
  port: 8080

spring:
  application:
    name: customer-service

  datasource:
    url: jdbc:mysql://localhost:3307/customerdb
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

  rabbitmq:
    host: rabbitmq
    port: 5672
    username: guest
    password: guest

  jackson:
    serialization:
      INDENT_OUTPUT: true

logging:
  level:
    root: INFO
